// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunSync.Api.Data;

#nullable disable

namespace RunSync.Api.Migrations
{
    [DbContext(typeof(RunSyncDbContext))]
    [Migration("20260517010418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RunSync.Api.Models.Entities.StravaActivity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<float>("AverageHeartrate")
                        .HasColumnType("float");

                    b.Property<float>("AverageSpeed")
                        .HasColumnType("float");

                    b.Property<float>("DistanceMeters")
                        .HasColumnType("float");

                    b.Property<bool>("IsManualEntry")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MovingTimeSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDateLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("TotalElevationGain")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartDateUtc");

                    b.HasIndex("UserId", "StartDateLocal");

                    b.ToTable("StravaActivities");
                });

            modelBuilder.Entity("RunSync.Api.Models.Entities.StravaToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StravaAthleteId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StravaTokens");
                });

            modelBuilder.Entity("RunSync.Api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RunSync.Api.Models.Entities.StravaActivity", b =>
                {
                    b.HasOne("RunSync.Api.Models.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RunSync.Api.Models.Entities.StravaToken", b =>
                {
                    b.HasOne("RunSync.Api.Models.Entities.User", "User")
                        .WithOne("StravaToken")
                        .HasForeignKey("RunSync.Api.Models.Entities.StravaToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RunSync.Api.Models.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("StravaToken");
                });
#pragma warning restore 612, 618
        }
    }
}
