// Controllers/AuthController.cs
// Handles user registration and login. Returns a JWT on success.
// This controller has no business logic — it validates input, delegates to services,
// and maps results to HTTP responses.
//
// Endpoints:
//   POST /api/auth/register  → creates a new user, returns JWT
//   POST /api/auth/login     → verifies credentials, returns JWT
//
// → Uses BCrypt.Net-Next for password hashing (never plaintext)
// → JWT generated by TokenService.cs → GenerateToken()
// → User persisted via RunSyncDbContext.cs

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunSync.Api.Data;
using RunSync.Api.Models.DTOs.Auth;
using RunSync.Api.Models.Entities;
using RunSync.Api.Services.Interfaces;

namespace RunSync.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class AuthController : ControllerBase
{
    private readonly RunSyncDbContext _db;
    private readonly ITokenService _tokenService;
    private readonly ILogger<AuthController> _logger;

    public AuthController(RunSyncDbContext db, ITokenService tokenService, ILogger<AuthController> logger)
    {
        _db = db;
        _tokenService = tokenService;
        _logger = logger;
    }

    /// <summary>
    /// Creates a new RunSync account. Returns 409 if the email is already registered.
    /// → Password is hashed with BCrypt work factor 12 before storage
    /// → On success, returns JWT via TokenService.cs → GenerateToken()
    /// </summary>
    [HttpPost("register")]
    [ProducesResponseType(typeof(AuthResponseDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> Register([FromBody] RegisterDto dto)
    {
        bool emailTaken = await _db.Users.AnyAsync(u => u.Email == dto.Email.ToLower());
        if (emailTaken)
            return Conflict(new { message = "An account with this email already exists." });

        User user = new()
        {
            Email = dto.Email.ToLower().Trim(),
            DisplayName = dto.DisplayName.Trim(),
            // Work factor 12 is the current OWASP recommendation for interactive logins
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(dto.Password, workFactor: 12),
            CreatedAt = DateTime.UtcNow
        };

        _db.Users.Add(user);
        await _db.SaveChangesAsync();

        _logger.LogInformation("New user registered: {Email} (Id={UserId})", user.Email, user.Id);

        return CreatedAtAction(nameof(Register), BuildAuthResponse(user));
    }

    /// <summary>
    /// Validates email/password and returns a JWT on success.
    /// Returns 401 for both "email not found" and "wrong password" — intentionally
    /// vague to prevent user enumeration attacks.
    /// → Password verified with BCrypt.Verify() which handles timing-safe comparison
    /// </summary>
    [HttpPost("login")]
    [ProducesResponseType(typeof(AuthResponseDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> Login([FromBody] LoginDto dto)
    {
        User? user = await _db.Users
            .FirstOrDefaultAsync(u => u.Email == dto.Email.ToLower());

        // Same response for "not found" and "wrong password" — prevents user enumeration
        if (user is null || !BCrypt.Net.BCrypt.Verify(dto.Password, user.PasswordHash))
        {
            _logger.LogWarning("Failed login attempt for email: {Email}", dto.Email);
            return Unauthorized(new { message = "Invalid email or password." });
        }

        _logger.LogInformation("User logged in: {Email} (Id={UserId})", user.Email, user.Id);

        return Ok(BuildAuthResponse(user));
    }

    private AuthResponseDto BuildAuthResponse(User user) => new()
    {
        Token = _tokenService.GenerateToken(user),
        DisplayName = user.DisplayName,
        Email = user.Email
    };
}

/*
 * ─── WHAT CONNECTS HERE ───────────────────────────────────────────────────────
 * This file is called by:   HTTP clients (frontend login/register forms)
 * This file calls into:     RunSyncDbContext.cs (user lookup + creation)
 *                           TokenService.cs (JWT generation)
 *                           BCrypt.Net-Next (password hashing + verification)
 * Next logical file to read: StravaController.cs (the next auth-gated flow)
 * ─────────────────────────────────────────────────────────────────────────────
 */
