// Models/DTOs/Auth/AuthResponseDto.cs
// Response body for both POST /api/auth/register and POST /api/auth/login.
// The frontend stores the JWT in localStorage and sends it as
// "Authorization: Bearer <token>" on all subsequent requests.
// → Built in AuthController.cs after successful login/registration
// → Token is generated by TokenService.cs → GenerateToken()

namespace RunSync.Api.Models.DTOs.Auth;

public class AuthResponseDto
{
    public string Token { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
}
